-- Declaração de variáveis
DECLARE @LANCAMENTO_SEM_CONTA INT = xxx;

DECLARE @LANCAMENTO_REFERENCIA INT;
DECLARE @NOVO_PEDIDOID INT;
DECLARE @STATUS_PAR INT = 0;
DECLARE @FORMA_PAGAMENTO_A_DEFINIR INT
DECLARE @PARCELA INT = 1
DECLARE @PARCELAS INT = 1
DECLARE @VALOR_TOTAL_LANCAMENTO REAL;
DECLARE @VALOR_TOTAL_PRODUTOS_PP REAL
DECLARE @VALOR_DESCONTO_TOTAL_PRODUTOS_PP REAL
-- Recupera o valor do lançamento com base no código
SET @VALOR_TOTAL_LANCAMENTO = (
    SELECT VALORTOTAL 
    FROM vwLancamentos 
    WHERE LancamentoID = @LANCAMENTO_SEM_CONTA
);


-- Obtém o ID de lançamento de referência baseado no valor e período
SET @LANCAMENTO_REFERENCIA = (
    SELECT TOP 1 LancamentoID
    FROM vwLancamentos
    WHERE ValorTotal = @VALOR_TOTAL_LANCAMENTO
      AND LancamentoID <> @LANCAMENTO_SEM_CONTA
      AND Emissao IS NOT NULL
      AND [Status] % 2 = 0
    ORDER BY LancamentoID DESC
);

SET @FORMA_PAGAMENTO_A_DEFINIR = (SELECT CÓDIGO FROM FORMASDEPAGAMENTO WHERE ESPÉCIE = 9)

PRINT('Lançamento Ref:')
PRINT(@LANCAMENTO_REFERENCIA)


----------------------------			PEDIDOS_PRODUTOS					----------------------------

--		PEDIDOS_PRODUTOS		--
SET @VALOR_TOTAL_PRODUTOS_PP = (
SELECT SUM((QDE * PREÇO) - DESCONTO)
	FROM PEDIDOS_PRODUTOS
WHERE LANCAMENTO = @LANCAMENTO_SEM_CONTA AND SUBITEM = 0 AND STATUS % 2 = 0 AND FATOR > 0)

SET @VALOR_DESCONTO_TOTAL_PRODUTOS_PP = (
SELECT SUM(DESCONTO)
	FROM PEDIDOS_PRODUTOS
WHERE LANCAMENTO = @LANCAMENTO_SEM_CONTA AND SUBITEM = 0 AND STATUS % 2 = 0 AND FATOR > 0)



----------------------------			LANÇAMENTOS_FORMASDEPAGAMENTO		----------------------------

INSERT INTO LANÇAMENTOS_FORMASDEPAGAMENTO
	([INCLUSAO] ,[EDICAO] ,[STATUS] ,[CONEXAOID] ,[LANCAMENTOID] ,[SP],[FORMADEPAGAMENTOID] ,[PARCELAS] ,[VALOR],
	[TEFID], [LANCAMENTODEVOLUCAO],[ORIGEMLANCAMENTOID],[PLANODEPAGAMENTOID] ,[TROCO],[DFEPAGAMENTOID])

SELECT
	[INCLUSAO],[EDICAO], @STATUS_PAR, [CONEXAOID], @LANCAMENTO_SEM_CONTA, [SP],@FORMA_PAGAMENTO_A_DEFINIR ,@PARCELAS,
	[VALOR], [TEFID], [LANCAMENTODEVOLUCAO],[ORIGEMLANCAMENTOID],[PLANODEPAGAMENTOID] ,[TROCO],[DFEPAGAMENTOID]

FROM LANÇAMENTOS_FORMASDEPAGAMENTO 
WHERE LANCAMENTOID = @LANCAMENTO_REFERENCIA



----------------------------		CONTAS		--------------------------------

INSERT INTO CONTAS ([LANÇAMENTO], [DATADAINCLUSÃO], [DATADEEDIÇÃO],[CONEXÃO], [NATUREZA], [STATUS], [DATADEVENCIMENTO],
		[DATADERECEBIMENTO], [CONEXÃODORECEBIMENTO], [DATADEPAGAMENTO], [CONEXÃODOPAGAMENTO], [VALORDACONTA],
		[VALORPAGO], [CONTACORRENTE], [SP], [PARCELA], [PARCELAS], [FORMADEPAGAMENTO])

SELECT @LANCAMENTO_SEM_CONTA, [DATADAINCLUSÃO], [DATADEEDIÇÃO],[CONEXÃO], [NATUREZA], @STATUS_PAR, [DATADEVENCIMENTO],
	[DATADERECEBIMENTO], [CONEXÃODORECEBIMENTO], [DATADEPAGAMENTO], [CONEXÃODOPAGAMENTO], @VALOR_TOTAL_PRODUTOS_PP,
	@VALOR_TOTAL_PRODUTOS_PP, [CONTACORRENTE], [SP], @PARCELA, @PARCELAS, @FORMA_PAGAMENTO_A_DEFINIR

FROM CONTAS
WHERE LANÇAMENTO = @LANCAMENTO_REFERENCIA

