
ALTER TABLE PRODUTOSPROMOCOES DROP COLUMN ASSUMEVALOR;
GO
ALTER TABLE PRODUTOSPROMOCOES ADD ASSUMEVALOR BIT;
GO
--DROP VIEW [DBO].[VWPRODUTOSPROMOCOES];
GO
ALTER VIEW [DBO].[VWPRODUTOSPROMOCOES] AS
SELECT PRODUTOPROMOCAOID, INCLUSAO, EDICAO, STATUS, ATIVO, PROMOCAONOME, PRODUTOID, PRECOID, PRECO, INICIO, CONCLUSAO, HORAINICIO, HORACONCLUSAO, DOM, SEG, TER, QUA, QUI, SEX, SAB, TIPODESCONTO, PAGUE, LEVE, APARTIRDE, UNIDADEID, SOMENTEDIASUTEIS, BALCAO, MESAS, CARTOES, DELIVERY, ENCOMENDAS, ASSUMEVALOR
FROM PRODUTOSPROMOCOES
GO
DROP VIEW [MOSAICO].[PRODUTOPROMOCAO];
GO
CREATE VIEW [Mosaico].[PRODUTOPROMOCAO] AS
SELECT PRODUTOPROMOCAOID ID, INCLUSAO, EDICAO, STATUS, ATIVO, PROMOCAONOME NOME, PRODUTOID, PRECOID, PRECO, INICIO, CONCLUSAO, HORAINICIO, HORACONCLUSAO, DOM, SEG, TER, QUA, QUI, SEX, SAB, TIPODESCONTO TIPO, PAGUE, LEVE, APARTIRDE, UNIDADEID ESTABELECIMENTOID, SOMENTEDIASUTEIS, MODALIDADERELACIONADA, BALCAO, MESAS, CARTOES, DELIVERY, ENCOMENDAS,ASSUMEVALOR
FROM PRODUTOSPROMOCOES;
GO
ALTER VIEW [MOSAICO].[PRODUTOPROMOCAO] AS
SELECT PRODUTOPROMOCAOID ID, INCLUSAO, EDICAO, STATUS, ATIVO, PROMOCAONOME NOME, PRODUTOID, PRECOID, PRECO, INICIO, CONCLUSAO, HORAINICIO, HORACONCLUSAO, DOM, SEG, TER, QUA, QUI, SEX, SAB, TIPODESCONTO TIPO, PAGUE, LEVE, APARTIRDE, UNIDADEID ESTABELECIMENTOID, SOMENTEDIASUTEIS, MODALIDADERELACIONADA, BALCAO, MESAS, CARTOES, DELIVERY, ENCOMENDAS,ASSUMEVALOR
FROM PRODUTOSPROMOCOES;
GO