CREATE TABLE TB_PRECOKM(
Id Int identity(1,1) PRIMARY KEY,
De [decimal](5, 2),
Ate [decimal](5, 2),
Preco [decimal](5, 2))
DELETE FROM TB_PRECOKM
INSERT INTO TB_PRECOKM(DE,ATE,PRECO) VALUES(10,10,5);
DBCC Checkident( TB_PRECOKM, reseed, 0)
--SELECT IDENT_CURRENT('TB_PRECOKM');
--SELECT ISNULL(PRECO,0) PRECO FROM TB_PRECOKM WHERE 24.3 BETWEEN DE AND ATE
--SELECT PRECO PRECO FROM TB_PRECOKM WHERE 24.3 BETWEEN DE AND ATE
--SELECT * FROM TB_PRECOKM w